### ISSUE TITLE
Key Errors When Running The Colab file

### ISSUE THREAD

**Issue by obscuresausage** [perth-seo-agency/automate-redirects-for-migrations#3]
Following the process of running two files through the colab file, I upload the origin CSV file which is one column called URL and then upload the destination CSV file of one column called URL. These columns both contain original site URLs and new site URLs from a development website.

I did a find a replace on the development website URLs to replace the hostname with the original site hostname for better matching.

Once it runs through the files and I have selected a column for matching, I end up with an error before it can output a file, I have attached an image of the errors I am getting.

![image](https://github.com/perth-seo-agency/automate-redirects-for-migrations/assets/84840336/55dde261-37b4-412a-8a66-9eaa3ce862d7)

**Comment by obscuresausage** [comment]
This was fixed by renaming the columns to address, this should be added to the instructions to ensure no errors like this happen again.

**Comment by perth-seo-agency** [comment]
Well done @obscuresausage, I appreciate the contribution.
